# Generated by Django 2.1.7 on 2020-08-06 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('occupancy', models.IntegerField(max_length=200)),
                ('usages', models.IntegerField(max_length=200)),
                ('inevents', models.IntegerField(max_length=200)),
                ('incleanevents', models.IntegerField(max_length=200)),
            ],
        ),
    ]
